---
head-message: "BossBar"
# Changing messages are here
# To set the percentage of the bar add {number%} before the message!
# Otherwise it takes the percentage that was there before.
# Example for a 25% filled: "{25%}This is a quarter filled bar >>"
changing-messages:
 - "{100%}&6&lBossAnnouncement"
# How fast the messages switch in seconds
change-speed: 5
# This changes the behaviour for multiple worlds
# Mode 0: see the bar in every world
# Mode 1: see ONLY in the worlds in the array
# Mode 2: DON'T see in worlds in the array
mode: 0
# Worlds: use the worldname, seperate with " , "
# Example: Mode 0, worlds: ["world", "lobby", "survival"]
worlds: []
# Formatting strings:
# %TPS%,
# %LOAD%,
# %UPTIME,
# %MOTD%,
# %ONLINE%,
# %MAX_ONLINE%,
# %SERVER_IP%,
# %IP%,
# %PING%,
# %NAME%,
# %KILLS%,
# %DEATHS%,
# %GROUP%,
# %MONEY%,
# %LEVEL_NAME%,
# %LEVEL_PLAYERS%,
# %ITEM_ID%,
# %ITEM_META%,
# %X%,
# %Y%,
# %Z%,
# %HOUR%,
# %MINUTE%,
# %SECOND%
# &0, &1, &2, &3, &4, &5, &6, &7, &8, &9, &a, &b, &c, &d, &e, &f, &k, &l, &m, &n, &o, &r
...
